service: edge-rewrite
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  deploymentBucket:
    name: dev-smartrx-mh-artifacts
    serverSideEncryption: AES256

functions:
  redirects:
    handler: handler.handler
    role: arn:aws:iam::855795768442:role/LambdaLoggingRole
    memorySize: 128
    timeout: 1

plugins:
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true
